### PR TITLE
Patch setup gitignore

### PR DESCRIPTION
**Pull request by matthewrobb**

### CODE REVIEW

**Comment by matthewrobb** [comment]
What I have done here is remove node_modules and npm-debug files from the repo and added a .gitignore file which allows you to exclude certain things from being verison controlled. Standard practice is to never include node_modules in the repo. Anyone pulling down the code is going to expect to run npm install.

**Comment by matthewrobb** [comment]
Dont accept this yet!

**Comment by matthewrobb** [comment]
The last commit is the one that fixes any issues caused by the major change. After this you should be able to pull down the project and just run npm install and then npm run start and be off to the races.

**Comment by Howie17** [comment]
Nice, thank you sir!

**Pull request merged**
